### ISSUE TITLE
Error: unverified X-Hub-Signature

### ISSUE THREAD

**Issue by sergibondarenko** [michaelnisi/deed#1]
I'm trying to use the deed to verify a GitHub webhook signature. And I receive an error. What am I doing wrong?

```
Error: unverified X-Hub-Signature
    at Verify.<anonymous> (/var/www/vicubic.com/node_modules/deed/index.js:37:40)
    at Verify.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Verify.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:438:10)
    at emitReadable (_stream_readable.js:432:7)
    at readableAddChunk (_stream_readable.js:183:13)
    at Verify.Readable.push (_stream_readable.js:130:10)
    at Verify.Transform.push (_stream_transform.js:128:32)
    at Verify._flush (/var/www/vicubic.com/node_modules/deed/index.js:25:8)
    at Verify.<anonymous> (_stream_transform.js:118:12)
    at Verify.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Verify.emit (events.js:185:7)
    at prefinish (_stream_writable.js:478:12)
    at finishMaybe (_stream_writable.js:486:7)
```

The webhook route code:

```
...
    app.post('/deploytomaster', function(req, res) {
        var deploy = spawn('sh', [ './scripts/deploy.sh' ]);

        deed('my_github_webhook_secret', req, function (err, req) {
            if (!err) {
                deploy.stdout.on('data', function (data) {
                    console.log(data);
                });

                deploy.on('close', function (code) {
                    console.log('Child process exited with code ' + code);
                });
                res.status(200).json({message: 'Github Hook received!'});
            } else {
                console.log(err);
            }
        });
    });
...
```

**Comment by michaelnisi** [comment]
Sorry about that. Please post the request headers.
